server:
  port: 8888
spring:
  application:
    name: order-consumer

eureka:
  client:
    # eureka client刷新本地缓存时间 默认30s
    registry-fetch-interval-seconds: 5
# ribbon 立即加载的服务
ribbon:
  eager-load:
    clients: order-service









