server:
  port: ${random.int(10000,19999)}
spring:
  application:
    name: order-consumer

eureka:
  client:
    service-url:
      defaultZone: http://online-master:8760/eureka,http://online-slave:8761/eureka
