spring:
  application:
    name: api-gateway
server:
  port: 1101
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  add-host-header: true
  #ignored-services: *
  #单实例配置：通过一组zuul.routes.<route>.path与zuul.routes.<route>.url参数对的方式配置
  routes:
    user-service:
      path: /user-service/**
      url: http://localhost:8080/
    sms-service:
      path: /api-sms/**
      serviceId: eureka-client-consumer-feign
  host:
    max-per-route-connections: 1000
    max-total-connections: 1000
ribbon:
  eager-load:
    enabled: true
    clients: eureka-client-consumer-feign






