server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    # 快速刷新配置解析 Eureka服务提供方修改如下配置
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    # 默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间配置，每隔这个时间会主动心跳一次  默认30s
    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: order-service





