server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    # 快速刷新配置解析 Eureka服务提供方修改如下配置
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    # 默认90s
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间配置，每隔这个时间会主动心跳一次  默认30s
    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: order-service

# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.yourpackage.*.entity
  global-config:
    # 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true








