server:
  port: 12001

spring:
  application:
    name: order-service


  datasource:
    hikari:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8
      connection-test-query: select 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka



