spring:
  application:
    name: eureka-client-provider

eureka:
  client:
    service-url:
      defaultZone: http://online-master:8760/eureka/


# 下线服务的用法 curl -X POST http://localhost:port/shutdown
endpoints:
  shutdown:
    # 启用shutdown 在切换服务的时候 可以实现优雅的下线服务
    enabled: true
    #禁用密码验证
    sensitive: false

# 设置端点访问
management:
  security:
    enabled: false



