spring:
  rabbitmq:
    addresses: localhost
    virtual-host: /
    username: guest
    password: guest
  application:
    name: stream-rabbit-demo
  cloud:
    stream:
      default-binder: boss


server:
  port: 12190
